### ISSUE TITLE
How to obtain a KEY?

### ISSUE THREAD

**Issue by AimeeChen** [RightMesh/HelloMesh#2]
![u4k jj7im3q _9i24b6rxxu](https://user-images.githubusercontent.com/22937496/32638393-024ff4c4-c5fa-11e7-9727-56fb26ef952c.png)

**Comment by bqkhiem96** [comment]
Same, I'm not able to register via my email.

**Comment by gramcracker** [comment]
Same here, developer.rightmesh.io/register_form.php will not open.

**Comment by FrazerSeymour** [comment]
Hi there - we're still working towards open beta but aren't there yet, so for now we aren't approving new accounts (and as you've noticed the registration form is currently closed). If you're looking to be a partner reach out to research@rightmesh.io, or keep an eye out for hackathons that we're attending and inviting people to try using the library at.
